### ISSUE TITLE
Formatting as per local standards

### ISSUE THREAD

**Issue by radar** [floere/phony#252]
If I have a number that's like `+610255502098`, can we get Phony to format it like: `(02) 5550 2098`? This is a common local format in Australia.

Similarly, with a number like `+12075550156`, we'd like it formatted like `(207) 555-0156`.

Is that possible?

**Comment by floere** [comment]
Hi Ryan!

It depends what you want. If you just want to format a number any which way, use the `format` option with the `%{}` interpolators - you have `cc`, `ndc`, `local`:

```ruby
ruby -e 'require "phony"; p Phony.format(Phony.normalize("+610255502098"), :format => "(%{ndc}) %{local}")'
ruby -e 'require "phony"; p Phony.format(Phony.normalize("+12075550156"), :format => "(%{ndc}) %{local}", :local_spaces => :-)'
```

However, I think you'd like to have that formatting in general – am I right?

**Comment by radar** [comment]
That first example you've given shows this `(2) 5550 2098`.

Yes I would like to have that formatting in general. I'd like to be able to specify a number and have Phony figure out what country that number's from and how to format it like that.

I don't mind hard coding it. It's just if phony can do it, then I'd prefer it if it did.

**Comment by floere** [comment]
> That first example you've given shows this (2) 5550 2098.

True. I forgot about the trunk code. So it should be (using the latest version):

```bash
ruby -e 'require "phony"; p Phony.format(Phony.normalize("+610255502098"), :format => "(%{trunk}%{ndc}) %{local}")' # => (02) 5550 2098
```

Also, I now understand your initial request better. There are quite a few formatting options in the README, for example here: https://github.com/floere/phony#national

I'll list some options.

## Using the `national` format.

You can get close to what you want using the `national` format:

```
ruby -e 'require "phony"; p Phony.format(Phony.normalize("+610255502098"), :format => :national)' # => "02 5550 2098"
ruby -e 'require "phony"; p Phony.format(Phony.normalize("+12075550156"), :format => :national)' # => "1 207 555 0156" (1 is the NANP trunk code, not the CC)
```

## Redefining a country definition

If you want NANP numbers to have a dash between local numbers, just redefine the country definition with e.g. `Phony["1"].with("1", local_space: "-")`:

```
ruby -e 'require "phony"; Phony["1"].with("1", local_space: "-"); p Phony.format(Phony.normalize("+12075550156"), :format => :national)'
"1 207 555-0156"
```

I am very open to add more options here, such as parentheses, if you need that.

> Yes I would like to have that formatting in general. I'd like to be able to specify a number and have Phony figure out what country that number's from and how to format it like that.
> I don't mind hard coding it. It's just if phony can do it, then I'd prefer it if it did.

If somebody has contributed a format, Phony does generally format the numbers as they are formatted in the country. But only if there are either official documents with a format definition, or there is overwhelming evidence – as any change to the default formatting is breaking for most users. One problem with this is that while the number structure is usually provided, the format isn't. So what I do is try to find out what it is – or trust locals.

When I added Australia, I tried to find out what the prevalent number formatting is – and it was unclear to me. Both `0408 173 868` and `(07) 3841 0643` seem to be in use.
Similarly with the NANP numbers.

Anyway, currently Phony takes you to `02 5550 2098` and `1 207 555 0156` – but not yet the parentheses. I'm happy to add an option for these, though – and make it the default for Australia, if you can make a case for it.

**Comment by floere** [comment]
I've found a reference to Australian number formatting: http://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers#Australia

> The area code is sometimes written within parentheses (0A) BBBB BBBB, but this usage is becoming less common.

So I'd go with what Phony provides with the national format.

For NANP numbers see http://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers#United_States.2C_Canada.2C_and_other_NANP_countries). I am open to adding parentheses around the NDC, and omitting the trunk code (`1`).

Let me know if you need any changes or if the `national` format is enough.

**Comment by radar** [comment]
Agreed on the AU format.

I'd love it if the U.S. national format did leave off the 1 and added parenthesis around the NDC.

**Comment by floere** [comment]
Ok, I'm convinced re U.S. national format. I'll work on it this weekend. Cheers!

**Comment by floere** [comment]
Released in 2.14.0.

**Comment by floere** [comment]
See some examples here: https://github.com/floere/phony/blob/master/spec/functional/format_spec.rb#L91-L105 Cheers!

**Comment by radar** [comment]
Excellent! Thanks @floere :)

**Comment by radar** [comment]
I don't see `format_spec.rb` anywhere in the repo?

**Comment by floere** [comment]
I should not have linked to master – I'm in the process of moving to QED specs, so the format options are described here: https://github.com/floere/phony/blob/master/qed/format.md Sorry!

**Comment by floere** [comment]
@radar My pleasure!

**Comment by manoharkshetty** [comment]
`Phony.format(Phony.normalize("+12075550156"), :format => "(%{ndc}) %{local}", :local_spaces => :-)` throws error `undefined method 'empty?' for nil:NilClass` 

ruby version 2.2.1
phony version 1.9

stack trace
```
NoMethodError: undefined method `empty?' for nil:NilClass
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/phony-1.8.0/lib/phony/country_codes.rb:60:in `format_cc_ndc_local'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/phony-1.8.0/lib/phony/country_codes.rb:48:in `formatted'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/phony-1.8.0/lib/phony.rb:79:in `format!'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/phony-1.8.0/lib/phony.rb:76:in `format'
	from (irb):2
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/skylight-0.6.1/lib/skylight/probes.rb:81:in `require'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/skylight-0.6.1/lib/skylight/probes.rb:81:in `require'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/xyz/code/arc/cfp/bin/rails:8:in `<top (required)>'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/commands/rails.rb:6:in `call'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:183:in `block in serve'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:156:in `fork'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:156:in `serve'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/xyz/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```
However it works fine with ruby version 2.2.1p85 
```
 -> ruby -e 'require "phony"; p Phony.format(Phony.normalize("+12075550156"), :format => "(%{ndc}) %{local}", :local_spaces => :-)'
"(207) 555-0156"
➜   ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
```
Fails with 2.2.2p95
```
➜   ruby -e 'require "phony"; p Phony.format(Phony.normalize("+12075550156"), :format => "(%{ndc}) %{local}", :local_spaces => :-)'
/Users/xyz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/phony-1.8.0/lib/phony/country_codes.rb:60:in `format_cc_ndc_local': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /Users/xyz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/phony-1.8.0/lib/phony/country_codes.rb:48:in `formatted'
	from /Users/xyz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/phony-1.8.0/lib/phony.rb:79:in `format!'
	from /Users/xyz/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/phony-1.8.0/lib/phony.rb:76:in `format'
	from -e:1:in `<main>'
➜  ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
```
Can anybody please let me know what am I missing?

**Comment by floere** [comment]
@manoharkshetty Hi there! Would it be a problem to upgrade your phony version? 1.9 is really old.

**Comment by manoharkshetty** [comment]
@floere Thanks a lot :)

**Comment by floere** [comment]
@manoharkshetty Cheers :) :rocket:
